FROM node:22-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install --production

COPY server.js .
COPY routes/ ./routes/
COPY middleware/ ./middleware/
COPY models/ ./models/
COPY controllers/ ./controllers/

EXPOSE 3000

CMD ["node", "server.js"]
