name: Add Default Label SSoC26

on:
  pull_request:
    types:
      - opened

jobs:
  label:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write

    steps:
      - name: Add SSoC26 label
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          gh pr edit "$PR_URL" --add-label "SSoC26"
